### ISSUE TITLE
I am operating under the assumption that this is a library used only on projects I am involved in

### ISSUE THREAD

**Issue by colons** [colons/instant-coverage#10]
I am liable to make decisions about breaking changes and documentation based on that assumption, even if I'm trying not to (and I am trying pretty hard already not to make breaking changes). This could prove to be a pretty serious problem.

If anyone but me is using instant coverage, this issue can be closed. **This is the only thing blocking a 1.0 release.**

**Comment by colons** [comment]
hey, @zenweasel @typeshige @reduxionist @mokelly @techdragon @kmmbvnr; can any of you help with this one? i can't see any public repos of yours using this, but your starring implies at least a passive interest

**Comment by reduxionist** [comment]
Happy to help; what exactly do you want help with?

**Comment by colons** [comment]
do you use instant coverage for any of your django sites?

**Comment by reduxionist** [comment]
I have used instant coverage on sites in development but not on anything that has gone into production yet.

**Comment by colons** [comment]
gotcha, thanks; please let me know if that changes

**Comment by colons** [comment]
Closed by #16. The next release will be 1.0.
