### ISSUE TITLE
Can't get some URLs to be excluded - Django 1.8

### ISSUE THREAD

**Issue by phoebebright** [colons/instant-coverage#14]
Am trying to get instant-coverage working on a large project of which most urls require user to be logged in.  Once I get the simple case of most things being excluded working, I'm going to have a go at getting it to check the ones that need a login are going to the login screen.

BUT I'm stuck trying to excude these five.  I have tried every combination I can think of to exclude but it persists in report them as errors, though other excludes, eg.          ('^library/',),  work fine.

Am I doing something wrong?

AssertionError: The following views are untested:

```
() ^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$ (None)
() ^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$ (None)
() ^reset/done/$ (password_reset_complete)
() ^uploads/(?P<path>.*)$ (None)
() ^ajax-upload/(?P<sig_id>\w+)/(?P<community_id>\w+)/(?P<parent>\w+)/$ (my_ajax_upload)
```

urls.py

```
 url(r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm'),
 url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm'),
 url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name="password_reset_complete"),

 url(r'^ajax-upload/(?P<sig_id>\w+)/(?P<community_id>\w+)/(?P<parent>\w+)/$', import_uploader, name="my_ajax_upload"),
url(r'^uploads/(?P<path>.*)$', login_required(xsendfileserve),{'document_root' : settings.ATTACHMENTS_ROOT}),
```

tests

```
uncovered_includes = [
  ...
    '^reset/',
    ('^reset/done/',),
    '^reset/done/',
    '/reset/done/',
    ('^uploads',),
    '^uploads',
    '/uploads',
    ('^uploads/',),
    '^uploads/',
    '/uploads/',
   ('^ajax-upload/(?P<sig_id>\w+)/(?P<community_id>\w+)/(?P<parent>\w+)/$',),
    ('^ajax-upload/',),
    '^ajax-upload/',
    '/ajax-upload/',
]
```

**Comment by colons** [comment]
in this case, you're probably better off using `uncovered_urls` than `uncovered_includes`; `uncovered includes` is only for excluding [url includes](https://docs.djangoproject.com/en/1.8/ref/urls/#django.conf.urls.include). the `()` at the beginning of the list of urls in that error means these urls are not part of any include. i agree that that is far from as clear as it should be.

when you include stuff in `uncovered_urls`, instant coverage doesn't care whether or not the url would actually render, all it cares about is whether another url match can be crossed off its checklist. so, something like the following would probably work:

```
uncovered_urls = [
    '/reset/0-0/',
    'reset/done/',
    'uploads/file/',
    'ajax-upload/0/0/0/',
]
```

you're right that the documentation and error messages are not clear enough about this, though, and i should do something about this; you basically have to look at the source to work out what the `()` in the list of URLs means, and that is super not good enough. please let me know if the above suggestion solves your problem; if it does, i will try to update the docs and that error message to be better about this.

thank you for using instant coverage!
